### ISSUE TITLE
Inconsistent linkify functionality

### ISSUE THREAD

**Issue by nlaz** [meetup/meetup-web-platform#158]
In order to support link HTML on `mup-web`, we ported the [linkify functionality](https://github.com/meetup/meetup-web-platform/blob/master/src/util/linkify.js) from [core/url.js](https://github.dev.meetup.com/meetup/meetup/blob/master/static/script/mu/core/url.js#L168) in chapstick. Turns out, there is more than one linkify function in Meetup classic and there is also the [Text.java implementation](https://github.dev.meetup.com/meetup/meetup/blob/master/modules/base/src/main/java/com/meetup/base/util/Text.java#L179) in chapstick. 

The issue is that the functionality is not consistent across platforms. For example, `Text.java` adds the `linkified` class and the `nofollow` tag. The new platform implementation doesn't have this but does include the `link` class and `noopener noreferrer` tags. I would like to propose adding some sort of standard across these utility functions, either in the new platform or in the classic platform. 

This is a non-blocker at the moment. Event descriptions return HTML descriptions using the `Text.java` linkify tool but we aren't using the HTML versions right now. However, I do think consistency matters and it should behave the same everywhere. Opening this issue to start a discussion amongst the platform team and consumers first.

**Comment by mmcgahan** [comment]
This makes sense to me - we won't need to add a `linkified` class to the platform `linkify` function because I think that's an old Sassquatch 1 class, but I think `nofollow` would be a good fit.

`noopener noreferrer` is probably worth back-porting to Text.java

**Comment by sadafie** [comment]
Ping. Should we open a ticket for this? Is it still an issue we should address?

**Comment by mmcgahan** [comment]
@nlaz I'm not sure what is actionable for the platform - should we update our linkify function or is it something that needs followup in chapstick? Should we document something somewhere?
