### ISSUE TITLE
mailer - add city into mail content

### ISSUE THREAD

**Issue by AmauryVanEspen** [meetup/meetup-web-platform#170]
Good evening

i would like to request an add-in about mailing feature.
I'm use to receive notification by email for new meetup group related to my interest,
however, i never know in which city the group takes place. Would it possible to add the location of the group in the mail notification.

Best

Amaury

**Comment by mmcgahan** [comment]
Hi @AmauryVanEspen this repo is being used as a library to build our web applications, and isn't related to the email system at Meetup. Feel free to email `support@meetup.com` with your feature request and we'll be sure to make a record of it. Thanks!
