### ISSUE TITLE
Async API validation with redux-form

### ISSUE THREAD

**Issue by mikespencer** [meetup/meetup-web-platform#271]
We recently did some validation via an API request for checking whether a particular pro network name and urlname are available ([PR](https://github.com/meetup/pro-web/pull/94)). This is fairly straight forwards with redux-form: return a Promise from a submit handler that resolves or rejects based on whether the form is valid or not. For a simple example, this is from their [documentation](http://redux-form.com/6.6.3/examples/submitValidation/):

```jsx
import { SubmissionError } from 'redux-form'

const sleep = ms => new Promise(resolve => setTimeout(resolve, ms))

function submit(values) {
  return sleep(1000) // simulate server latency
    .then(() => {
      if (![ 'john', 'paul', 'george', 'ringo' ].includes(values.username)) {
        throw new SubmissionError({ username: 'User does not exist', _error: 'Login failed!' })
      } else if (values.password !== 'redux-form') {
        throw new SubmissionError({ password: 'Wrong password', _error: 'Login failed!' })
      } else {
        window.alert(`You submitted:\n\n${JSON.stringify(values, null, 2)}`)
      }
    })
}

```

However, the platform doesn't support `fetch` type api requests that return a promise, so this is roughly the workaround approach we had to take:

```jsx
export class MyReduxFormContainer extends React.Component {

	validating = false;

	componentWillReceiveProps(props) {
		// if the component should be validating and the api request is not in flight
		if (this.validating && !props.inFlight.includes(VALIDATE_FROM_API_REF)) {
			let validationErrors = {};

			// handle generic api failures
			if (props.validatedFromApi.error) {
				validationErrors = {
					_error: 'Sorry, something went wrong. Please try again.',
				};
			} else {
				// api request success

				// get the values we need from the response
				const {
					name_available,
					urlname_available,
				} = props.validatedFromApi.value;

				if (!name_available) {
					validationErrors = {
						...validationErrors,
						pro_account: 'This name is not available',
					};
				}

				// check that the urlname is valid
				if (!urlname_available) {
					validationErrors = {
						...validationErrors,
						urlname: 'This URL is not available',
					};
				}
			}

			if (Object.keys(validationErrors).length) {
				// if there are validation or api errors, reject the promise that was
				// returned from the submit handler
				this.rejectValidationPromise(new SubmissionError(validationErrors));
			} else {
				// if everything is valid, resolve the promise returned from the submit
				// handler
				this.resolveValidationPromise();
			}

			// set the validating flag back to false
			this.validating = false;
		}
	}

	handleSubmit = (formValues) => {
		// set a flag while we are supposed to be validating
		this.validating = true;

		// call an action that triggers the API_REQUEST
		this.props.actions.validateFromAPI(formValues);

		// redux-form expects a promise returned from a submit handler function for
		// async validation.
		return new Promise((resolve, reject) => {
			// expose the resove/reject functions to resolve the promise when the
			// api request completes or fails.
			this.resolveValidationPromise = resolve;
			this.rejectValidationPromise = reject;
		});
	};

	render() {
		return (
			<MyReduxForm onSubmit={this.handleSubmit} />
		);
	}
}

export function mapStateToProps(state) {
	return {
		validatedFromApi: state.api[VALIDATE_FROM_API_REF] || {},
		inFlight: state.api.inFlight || [],
	};
}

export function mapDispatchToProps(dispatch) {
	return {
		actions: bindActionCreators(actionCreators, dispatch),
	};
}

export default connect(mapStateToProps, mapDispatchToProps)(MyReduxFormContainer);
```

If there were something in the platform that supported making promised based api requests that resolved with the response then we could skip a lot of the workaround code (eg: exposing resolve/reject from the promise, setting a validating flag) and do something more like:

```jsx
export class MyReduxFormContainer extends React.Component {
	handleSubmit(formValues) {
		// maybe some sort of platform defined `fetch` function that acts like fetch,
		// but takes a query and goes through the platforms api layer and may even
		// update the redux store if needed. The important thing here though (no matter the 
		// details of the implementation) is that the `thing` doing the api request
		// returns a promise that resolves with the response.
		return this.props.actions.fetch(validateFromAPIQuery(formValues))
			.then((response) => {
				let validationErrors = {};

				// handle generic api failures
				if (response.error) {
					validationErrors = {
						_error: 'Sorry, something went wrong. Please try again.',
					};
				} else {
					// api request success

					// get the values we need from the response
					const {
						name_available,
						urlname_available,
					} = response.value;

					if (!name_available) {
						validationErrors = {
							...validationErrors,
							pro_account: 'This name is not available',
						};
					}

					// check that the urlname is valid
					if (!urlname_available) {
						validationErrors = {
							...validationErrors,
							urlname: 'This URL is not available',
						};
					}
				}

				if (Object.keys(validationErrors).length) {
					throw new SubmissionError(validationErrors);
				}
			});
	};

	render() {
		return (
			<MyReduxForm onSubmit={this.handleSubmit} />
		);
	}
}

export function mapStateToProps(state) {
	return {};
}

export function mapDispatchToProps(dispatch) {
	return {
		actions: bindActionCreators(actionCreators, dispatch),
	};
}

export default connect(mapStateToProps, mapDispatchToProps)(MyReduxFormContainer);
```

To me that is much more cleaner. If redux-form is something that may be used more widely on platform based apps, I think we should talk about (or at least start thinking about) ways to simplify this type of async validation.

**Comment by mmcgahan** [comment]
It looks like this is a relatively well-known limitation of redux-form - [this article](http://randycoulman.com/blog/2016/05/03/redux-and-forms-and-apis-oh-my/) covers the issue with respect to a similar 'sync middleware' package called redux-api-middleware in a bit more detail and provides a pretty nice generic solution (with an update in a separate article to work with redux-form v6). However, it is dependent on an undocumented feature of redux-api-middleware that returns a promise from the initial 'REQUEST' action, which can then be consumed wherever you called `dispatch` on it.

I'll look more into configuring sync middleware to return a Promise to the dispatcher if possible - the resulting implementation looks really slick.

**Comment by mmcgahan** [comment]
I'm actually wondering if it would make sense to put a promise into `inFlight` that would resolve when the corresponding request returned... I don't think that would be too tricky and it would avoid jumping through hoops inside the component.

```js
state.api.inFlight = {
  [ref1]: Promise,
  [ref2]: Promise,
};
// ...
mapStateToProps(state) {
  myInFlightSubmit: state.api.inFlight[MY_REF],  // a Promise if submit is inflight, otherwise empty
}
componentWillReceiveProps(nextProps) {
  if (
    nextProps.myInFlightSubmit &&
    nextProps.myInFlightSubmit.status !== 'resolved' // i would probably have to monkey-patch this into the Promise
  ) {
    myInFlightSubmit.then(response => ...);
  }
}
```

**Comment by mikespencer** [comment]
Awesome, yeah either way seems pretty solid. From the consumer standpoint, if there is a way we can just trigger an api request that then gives access to a promise that resolves or rejects based on that api response, then things get much simpler and cleaner with redux-form (however it's implemented). 

I think the idea of returning a promise for in flight requests makes a lot of sense. However, one thing that I did notice is that the `componentWillReceiveProps` would be triggered several times while the api request was in flight, since a bunch of actions would be triggered, some of them updating the redux store... eg all of these actions are triggered when I click the submit button:

<img width="307" alt="screen shot 2017-05-04 at 7 05 54 pm" src="https://cloud.githubusercontent.com/assets/847987/25728405/ddd6c3da-30fc-11e7-9ab2-e0173bd302d4.png">

Just thinking that we may accidentally end up getting into a situation where we are adding a bunch of `.then`'s when we only need the one. I'm sure theres a good way around that, but just wanted to mention it.

**Comment by mmcgahan** [comment]
Ticket created https://meetup.atlassian.net/browse/WP-334
