### ISSUE TITLE
MWP modules

### ISSUE THREAD

**Issue by mmcgahan** [meetup/meetup-web-platform#281]
As this repo has stabilized, its underlying structure has become better defined, but the current module structure makes it difficult to work with features in isolation, and the scope of particular updates is initially difficult to determine because it's hard to get a sense of how many files might need to be touched.

I'd like to change that by restructuring the platform to be more clearly modular, with explicit entry points for consumer applications rather than the 'export all the things' setup we currently have. The module organization would also aim to have as few dependencies between modules as possible, so that updates can be confined to individual modules - in effect, it would be multiple independent 'packages' in a single repo.

This work would follow on from refactoring the server-side modules as plugins (outline copied over from [this Google Doc](https://docs.google.com/document/d/1o14_iO1Ak_QksizmKRI2KYv-IWB_Antg_wFCYBjgYNU/edit)):

### `server` (Hapi)
- [x] startup utils - https://meetup.atlassian.net/browse/WP-417

#### Hapi Plugins

- [x] ~~tracking - https://meetup.atlassian.net/browse/WP-318~~
- [x] ~~api - https://meetup.atlassian.net/browse/WP-319~~
- [x] react app renderer - https://meetup.atlassian.net/browse/WP-320
- [x] ~~service worker - wait for https://meetup.atlassian.net/browse/WP-321~~
- [x] click tracking - this interacts with Redux, fetchUtils, and the server routes - need to figure out how to make it a more coherent module

### ~~`router`~~
- [x] ~~browser: React Router helpers - https://meetup.atlassian.net/browse/WP-337~~

### `render` (React+Redux helpers)
- https://meetup.atlassian.net/browse/WP-416
- [x] `server`
  - ServerApp (TBD)
  - `dom.jsx`
  - `createServerStore`
- [x] `browser`
  - BrowserApp
  - `createBrowserStore`
- [x] `core`
  - `<PlatformApp />`
  - [ ] middleware/epics
  - [ ] platform reducer
  - [ ] `fetchUtils`

### ~~(optional) MWP build/run CLI~~
- [x] ~~described in Google doc~~

**Comment by mattkime** [comment]
nothing to add except that it looks like a good plan.

**Comment by eilinora** [comment]
@mmcgahan, Are there any down the chain changes that teams next be aware of, thinking of usages in Pro and MUP repo's?

**Comment by mmcgahan** [comment]
@eilinora at the moment I don't think there will be much if any change to the public interface besides tweaking some import paths - hopefully the sort of thing that can be done with a simple find-and-replace.

Any breaking API changes will be made very carefully, potentially with a deprecation period.

**Comment by mmcgahan** [comment]
done
