### ISSUE TITLE
The `Redirect` component without a `permanent` param still does a 301 redirect

### ISSUE THREAD

**Issue by aquillano** [meetup/meetup-web-platform#328]
### Description
`<Redirect to={generateClassicUrl(locale, '/login/')} />`
No `permanent` param ^
Still does a 301 redirect.

### Links
[Example on my branch](https://github.com/meetup/mup-web/blob/042971017783a0e9d4b9cea0b0a8efe5561b5e1a/src/app/group/event/schedule/EventScheduleContainer.jsx#L50)

### Images
<img width="750" alt="cloudapp annotation 2017-07-18 at 1 40 27 pm" src="https://user-images.githubusercontent.com/206505/28383933-d1135a08-6c90-11e7-8306-10ca8e6e80c4.png">

**Comment by mmcgahan** [comment]
Moved to https://meetup.atlassian.net/browse/WP-419
