### ISSUE TITLE
Combobox not working properly

### ISSUE THREAD

**Issue by Beelzenef** [meetup/meetup-web-platform#502]
I've been using Meetup web version on my phone and this has been happening since then. When selecting filters for meetups around me, this combobox does not work properly: header and arrow button work like independent elements instead of working together 😢

![capture 2018-06-03 at 8 18 42](https://user-images.githubusercontent.com/6389665/41333628-cb9902b2-6ee2-11e8-92c4-8679b39b2948.png)

**Comment by mmcgahan** [comment]
Hi @Beelzenef - the problem you're seeing is actually from a different part of the Meetup application than what is covered by the code in this repo - the best place to report it is using the 'Get help' button at https://help.meetup.com/hc/

Thanks!
