### ISSUE TITLE
How to save or print a meetup page?

### ISSUE THREAD

**Issue by haimivan** [meetup/meetup-web-platform#622]
Hi,

I hope I address my question at the right place?

I would like to print or save the contents of a meetup event, e.g.: https://www.meetup.com/London-Data-Science-Journal-Club/events/262019020

Presently printing with chrome or firefox results in a pdf where all the details and comments are missing. 

Saving it as a html page apparently saves the details and comments, but accessing the html page later without an internet connection does not show anything in the browser.

What can I do to perform my task?

Thanks in advance.

**Comment by haimivan** [comment]
my question is still not solved

**Comment by VirtualDisk** [comment]
hi there, I think this link would be most helpful to you: https://help.meetup.com/
